CREATE TABLE IF NOT EXISTS AdminUsers (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Classrooms (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS TimeSlots (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, start_time TEXT NOT NULL, end_time TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Bookings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    classroom_id INTEGER NOT NULL,
    timeslot_id INTEGER NOT NULL,
    booking_date TEXT NOT NULL,
    grade TEXT NOT NULL,
    purpose TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (classroom_id) REFERENCES Classrooms(id) ON DELETE CASCADE,
    FOREIGN KEY (timeslot_id) REFERENCES TimeSlots(id) ON DELETE CASCADE,
    UNIQUE (classroom_id, timeslot_id, booking_date)
);